silverlogic/baseapp-backend

baseapp-core/setup.cfg
baseapp-core/testproject/requirements.txt
baseapp-reactions/setup.cfg

mostly because we might want to support both django 3 and 4
but also for security issues, I think its better to leave for the projects to freeze the minor versions, otherwise minor upgrades would need to come from baseapp_core first, the benefit of having baseapp_core freeze the minor versions is that we can deliver updates to projects using baseapp_core, but to achieve this we would need to not freeze the minor version of baseapp_core in the project's requirements
thoughts?

make install_requires more flexible on baseapp_core

---

.github/workflows/publish-actions.yml
.github/workflows/publish-workflow-test.yml
.github/workflows/publish-workflow.yml
baseapp-cloudflare-stream-field/setup.cfg
baseapp-payments/setup.cfg

Deployments through the releases where still not working, turns out that secrets don't get propagated into reusable workflows so you need to specify to inherit them. I thought it was the lack of environments at the beginning but I'm leaving it bec I kinda liked to have secrets per environment instead

HOTFIX: Deployment environments

---

baseapp-auth/baseapp_auth/rest_framework/change_email/views.py
baseapp-auth/baseapp_auth/rest_framework/users/views.py
baseapp-drf-view-action-permissions/README.md
baseapp-drf-view-action-permissions/baseapp_drf_view_action_permissions/tests/test_integration.py

Basically just by using `queryset =` on viewset the ASGI sometimes complains we are trying to use a sync operation on async context.

Fix SynchronousOnlyOperation when using ASGI

---

baseapp-auth/baseapp_auth/rest_framework/urls/auth_authtoken.py
baseapp-auth/baseapp_auth/rest_framework/urls/auth_jwt.py
baseapp-auth/baseapp_auth/tests/integration/api_v1/test_login.py
baseapp-auth/testproject/urls.py

The refresh path was not working for me and we were getting some warnings about a trailing slash. This should fix the paths

BA-1173: Fix auth URL paths

---

baseapp-auth/baseapp_auth/rest_framework/urls/auth_authtoken.py
baseapp-auth/baseapp_auth/tests/integration/api_v1/test_login.py
baseapp-auth/testproject/urls.py

We agreed that all auth suff should start with the `auth` prefix and the simple token urls do need the slash for that

HOTFIX: Add slash to simple token endpoint back

---

baseapp-core/baseapp_core/management/commands/generate_uml.py

Sometimes we can get a ContentType that doesn't exist anymore as a model

Skip non-existint models from generate_uml

---

baseapp-message-templates/README.md
baseapp-message-templates/baseapp_message_templates/custom_templates.py
baseapp-message-templates/setup.cfg

* remove previous logic that was programmatically replacing the `{% block_content %}` with the child's content and use` render_to_string `'s context instead
*  sanitize the final HTML content
* remove `{% load my_filters %}`  since since wasn't being used and could've be replaced by [jinja2 custom filters](https://jinja.palletsprojects.com/en/3.1.x/api/#writing-filters)

Update default email template and sanitize template content

---

baseapp-auth/README.md
baseapp-auth/baseapp_auth/apps.py
baseapp-auth/baseapp_auth/rest_framework/jwt/serializers.py
baseapp-auth/baseapp_auth/rest_framework/jwt/tokens.py
baseapp-auth/baseapp_auth/settings.py
baseapp-auth/setup.cfg

This fixes the issues with the user update flows, where the token has stale data. Whenever we update the user's data, we can just call `refreshAccessToken(ACCESS_COOKIE_NAME, REFRESH_COOKIE_NAME)` on success and that should get a new access token with the fresh user data and save it to the cookie. In my tests I also updated the useUser hook to be like the following:
```
import { useEffect, useState } from 'react'
import { getUser } from '@baseapp-frontend/authentication'
import { IUser } from 'types/user'
export const useUser = () => {
const [user, setUser] = useState<Partial<IUser> | null>(null)
useEffect(() => {
const syncGetUser = async () => {
setUser(await getUser())
}
syncGetUser()
}, [])
return user
}
```
because I wasn't sure if the getUser function can be used directly in a react …

BA-1305: Inject up-to-date claims to access token on refresh

---

baseapp-core/baseapp_core/models.py
baseapp-core/setup.cfg
baseapp-url-shortening/baseapp_url_shortening/admin.py
baseapp-url-shortening/baseapp_url_shortening/models.py
baseapp-url-shortening/baseapp_url_shortening/tests/integration/test_url_shortening.py
baseapp-url-shortening/setup.cfg
baseapp-url-shortening/testproject/urls.py

Url shortening view should use /v1 so we can use `NEXT_PUBLIC_API_BASE_URL = app.tsl.io/v1` (front url + /v1)
The redirection order should work like that:
* user access shortened url -> `app.tsl.io/c/123abc`
* user gets redirected to `app.tsl.io/v1/c/123abc`
* the backend returns the full url and user is redirected to `app.tsl.io/some-route`

ELITE-497: baseapp url shortening pointing to /v1

---

baseapp-core/baseapp_core/channels.py
baseapp-core/baseapp_core/tests/test_jwt_auth_middleware.py
baseapp-core/setup.cfg

* Context:
This PR introduces a new `JWTAuthMiddleware` to handle JWT authentication for WebSocket connections in the ASGI application
* What was done:
* validates and/or refreshes JWT tokens provided in the scope subprotocol
* sets the authenticated user in the connection scope
* handles cases for invalid tokens, missing tokens, and inactive users
Note:
* I added the new `JWTAuthMiddleware` into `baseapp-core` package because the `TokenAuthMiddleware` was already there. but I don't know if that's the best place to add it. Maybe `baseapp-auth`?

ELITE-671: implement jwt middleware for ASGI application

---

.github/workflows/project-workflow.yml

Version 5.1 got released a few days ago and is breaking tests, this freezes django version to 5.0.x for the time being

fix tests for django 5.0

---

baseapp-core/baseapp_core/tests/test_case_insensitive_fields.py
baseapp-core/baseapp_core/tests/test_middleware.py
baseapp-core/baseapp_core/tests/test_random_name_generators.py
baseapp-core/baseapp_core/tests/test_token_generator.py

**Acceptance Criteria**
baseapp-core is missing proper tests for a bunch of utils
https://github.com/silverlogic/baseapp-backend/tree/master/baseapp-core
Although there is a test there for baseapp_core.channels.JWTAuthMiddleware, it is not currently running on the CI/CD flow because the testproject is incomplete. So for this story tests should run on CI/CD flow. Follow this PR as an example on how to get this done https://github.com/silverlogic/baseapp-backend/pull/130
Not looking to get 100% test coverage under this story, we can start with very simple stuff like:
**random_name_in
random_dir_in
TokenGenerator
CaseInsensitiveEmailField
CaseInsensitiveTextField
CaseInsensitiveCharField
HistoryMiddleware**
Would be perfect if we can cover some of the rest framework and graphql helpers as …

baseapp-core:  BA-1627 increase tests coverage

---

baseapp-payments/baseapp_payments/serializers.py
baseapp-payments/setup.cfg

Fix for the error:
TypeError: subscription_start_request() got an unexpected keyword argument 'price'
It happens when trying to call the function subscribe from a customer instance.
https://www.loom.com/share/1a7752c982054b00828ee3f5bac496b9

baseapp-payments: customer subscribe items fix

---

baseapp-chats/baseapp_chats/graphql/mutations.py
baseapp-chats/baseapp_chats/graphql/object_types.py
baseapp-chats/baseapp_chats/permissions.py

**Acceptance Criteria**
- Given I click on the "Leave Group" button in the 3 dots menu, when the action is triggered, then I should see a confirmation prompt asking if I am sure I want to leave the group.
- Given I am the sole admin in the group chat, then the confirmation dialog should inform me prompt me to select a new admin before leaving and informing me if I don't, then the most senior member will be the new admin.
- Given there are other admins besides me in the group then only display a the same confirmation dialog a normal member would have when leaving the group chat.
- Given I confirm that I want to leave the group, then I should no longer see the group in my chat list and stop receiving updates of messages on that group.
We are going to do a hard delete for that Group Chat for …

baseapp-chats [BA-2108]: leave group as admin

---

baseapp-auth/baseapp_auth/graphql/object_types.py
baseapp-auth/baseapp_auth/models.py
baseapp-auth/baseapp_auth/tests/unit/test_users.py

The short name is currently equal to the email address of a user, so the graphql request
```
allProfiles {
edges {
node {
owner {
shortName
}
}
}
}
```
produces a list of email addresses of signed up users (for any user who is authenticated). Since we do not want to expose email addresses, this removes `shortName` (it is not used on the frontend).

baseapp-auth: Remove short name

---

baseapp/baseapp/activity_log/permissions.py

add PERM_VIEW_NODE_DIFF to the activity log
In the template, custom permission has been added to activity log

baseapp.activity_logs: add PERM_VIEW_NODE_DIFF permission

---

baseapp/baseapp/activity_log/graphql/filters.py
baseapp/baseapp/activity_log/tests/test_graphql_queries.py

Description
As a user, on the Baseapp Activity Log,I would like to Filter activity entries by date, In order to quickly search for activities made in specific periods of time.
Acceptance Criteria 
Context
The objective of this story is to implement a filter that reduces the amount of activity logs displayed in order to search for logs in a specific period of time. 
Business Rules
Given I am a user searching for specific activites, when I use the date filters, Then the system shall display all activity logs that occurred from the start date through the end date, inclusive of both dates.
The system must provide a user-friendly interface for selecting a start date and an end date for filtering the activity logs.
Make sure the component complies with the current implemented Design System
The …

baseapp.activity_logs: filter by date

---

baseapp/baseapp_pages/graphql/mutations.py
baseapp/baseapp_pages/graphql/object_types.py
baseapp/baseapp_pages/permissions.py
baseapp/baseapp_pages/tests/test_delete_mutation.py
baseapp/baseapp_pages/tests/test_edit_mutation.py
baseapp/baseapp_pages/tests/test_get_queries.py

fix baseapp_pages tests and permissions by using app_label instead of hardcoded baseapp_pages

baseapp_pages: fix tests and permissions

---

baseapp-profiles/baseapp_profiles/graphql/mutations.py
baseapp-profiles/baseapp_profiles/models.py
baseapp-profiles/baseapp_profiles/tests/test_graphql_mutations_update.py
baseapp-profiles/baseapp_profiles/tests/test_url_path.py
baseapp-profiles/setup.cfg
baseapp/baseapp_organizations/tests/test_graphql_mutations_create.py

**Acceptance Criteria 
Context**
Even though the username field exists, right now we don't have any way for users to setup their username in BA. And they are important for the different social feature that we have.
**Business Rules - Automatic Username Creation**
- Given I have successfully sign up and my user is created, automatically create a username using the name. (no spaces)
- If the generated username already exists, append a number at the end, incrementing the number until a unique username is established.
- The username must be a minimum of 8 characters long. If the name is shorter than 8 characters, append random digits until it meets the requirement.
- Users should not contain special characters
**Business Rules - Edit Username**
- Parse slashes on username and profile page so …

baseapp-profiles[BA-2244]: edit/generate username for Profile

---

baseapp/baseapp_chats/graphql/subscriptions.py
baseapp/baseapp_chats/tests/test_graphql_subscriptions.py

**Acceptance Criteria** 
**Context**
Loom: [https://www.loom.com/share/9bcd130aa70f476fa3cebbb53ba338e0](https://www.loom.com/share/9bcd130aa70f476fa3cebbb53ba338e0)
**Business Rules**
- Given I input text into the message box, when I send the message, then the message box should become empty immediately
- Given I have sent a message, the message should be displayed in the chat history quickly.
- If a message fails to be send, just remove the message from the chat history.
- Display a toast informing this to the user.
- Disable the send button until we know the message sending request was resolved, either successful or failed, 
**Approvd** 
[https://app.approvd.io/silverlogic/BA/stories/38918](https://app.approvd.io/silverlogic/BA/stories/38918)

baseapp-chats [BA-2236]: Change message subscription to not publish to sender
