silverlogic/baseapp-backend

- .github/workflows/publish-actions.yml
Didn't realize that the cloudflare package was missing its publishing action
> HOTFIX: Add cloudflare publish action

- baseapp-auth/baseapp_auth/tests/integration/api_v1/test_register.py
- baseapp-auth/baseapp_auth/tests/integration/api_v1/test_users.py
- baseapp-auth/baseapp_auth/tests/unit/test_users.py
- baseapp-core/MANIFEST.in
use get_user_model instead of concrete User model
update baseapp-core MANIFEST
> enable tests import inside target project tests

- baseapp-auth/baseapp_auth/rest_framework/register/serializers.py
- baseapp-auth/setup.cfg
Add password validations on register
> BA-1221-be-register-password-validations

- baseapp-message-templates/README.md
- baseapp-message-templates/baseapp_message_templates/custom_templates.py
- baseapp-message-templates/setup.cfg
* change to `render_to_string` loader
> BA: alter template loader

- baseapp-comments/setup.cfg
- baseapp-pages/setup.cfg
I forgot to bump up the versions for baseapp-pages and baseapp-comments on [PR#107](https://github.com/silverlogic/baseapp-backend/pull/107) 😅
> Bump baseapp-comments and baseapp-pages versions up

- baseapp-url-shortening/baseapp_url_shortening/admin.py
- baseapp-url-shortening/baseapp_url_shortening/models.py
- baseapp-url-shortening/baseapp_url_shortening/utils.py
- baseapp-url-shortening/setup.cfg
* expose `public_short_url` instead of `short_url_path`
> BA: public shorten url

- baseapp-core/MANIFEST.in
- baseapp-core/setup.cfg
[BA] ❌ Broken logo displayed in email
>  Broken logo displayed in email

- README.md
Add readme instructions about how to publish a new version of package
> Publishing a package README instructions

- baseapp-blocks/baseapp_blocks/admin.py
- baseapp-blocks/setup.cfg
- baseapp-comments/baseapp_comments/admin.py
- baseapp-comments/setup.cfg
- baseapp-follows/baseapp_follows/admin.py
- baseapp-follows/setup.cfg
- baseapp-profiles/baseapp_profiles/admin.py
- baseapp-profiles/setup.cfg
- baseapp-ratings/README.md
- baseapp-ratings/baseapp_ratings/admin.py
- baseapp-ratings/baseapp_ratings/graphql/mutations.py
- baseapp-ratings/baseapp_ratings/tests/test_graphql_mutations.py
- baseapp-ratings/setup.cfg
- baseapp-reactions/baseapp_reactions/admin.py
admin can be very slow if we don't use raw_id_fields on ForeignKey to this big tables
> make use of raw_id_fields on admin

- baseapp-auth/setup.cfg
Just bumping up auth version to be able to make the release of the avatar hotfix https://github.com/silverlogic/baseapp-backend/pull/153
> bump auth version to make hotfix release

- baseapp-profiles/baseapp_profiles/graphql/mutations.py
- baseapp-profiles/setup.cfg
Added `phone_number` field to `ProfileUpdateSerializer` on `baseapp-profiles`
> BA-1599: add phone_number to ProfileUpdateSerializer

- baseapp-profiles/baseapp_profiles/graphql/mutations.py
- baseapp-profiles/baseapp_profiles/tests/test_graphql_mutations_update.py
- baseapp-profiles/setup.cfg
Enable removing images when updating profiles from `baseapp-profiles`
> baseapp-profiles: enable image deletion on update

- baseapp-auth/baseapp_auth/emails.py
- baseapp-auth/baseapp_auth/templates/users/emails/remove-superuser-notification-email-subject.txt.j2
- baseapp-auth/baseapp_auth/tests/unit/test_emails.py
- baseapp-auth/setup.cfg
Fix 500 error
```
TemplateDoesNotExist at /admin/users/user/2/change/
users/emails/remove-superuser-notification-email.txt.j2
```
And this also includes a test to detect the same error.
> Fix remove superuser e-mail

- baseapp-chats/baseapp_chats/graphql/mutations.py
- baseapp-chats/baseapp_chats/graphql/object_types.py
- baseapp-chats/baseapp_chats/permissions.py
- baseapp-chats/baseapp_chats/tests/test_graphql_mutations.py
- baseapp-chats/setup.cfg
**Acceptance Criteria** 
_Leave group - As a Member_
- Given I am a member of a Group shat, I should see a 3 dots menu in the Chat room title area.
- Given I am a member of a group chat, when click the 3 dots menu in the Group Title, then I should see a "Leave Group" option prominently displayed.
- Given I click on the "Leave Group" button, when the action is triggered, then I should see a confirmation prompt asking if I am sure I want to leave the group.
- Given I confirm that I want to leave the group, then I should no longer see the group in my chat list and stop receiving updates of messages on that group.
**We are going to do a hard delete for that Group Chat for that user.**
> baseapp-chats [BA-2047]: leave group

- baseapp-profiles/baseapp_profiles/models.py
- baseapp-profiles/baseapp_profiles/signals.py
- baseapp-profiles/setup.cfg
- baseapp/baseapp/activity_log/tests/test_graphql_queries.py
- baseapp/setup.cfg
**Description**
**Acceptance Criteria** 
From settings > profile - change username and save changes. The changes will be shown there. 
But if you logged in to different browser or incognito mode, the changes is not showing there.
**Video**: [https://www.loom.com/share/f60d3b6f98f04d75afc18441f7354cd8?sid=bd4f7b5c-0533-413e-9199-d598acdcee53](https://www.loom.com/share/f60d3b6f98f04d75afc18441f7354cd8?sid=bd4f7b5c-0533-413e-9199-d598acdcee53)
Bug Catcher: Selim Reza 
**Approvd** 
[https://app.approvd.io/silverlogic/BA/stories/38227](https://app.approvd.io/silverlogic/BA/stories/38227)
> baseapp-profiles [BA-2172] Do not overwrite profile name with user name

- baseapp/baseapp_core/graphql/views.py
name sentry transaction with the graphql query name and type (mutation, query or subscription) making sentry data more useful for graphql
> baseapp-core[graphql]: improve sentry instrumentation

- baseapp-chats/README.md
- baseapp-chats/baseapp_chats/graphql/mutations.py
- baseapp-chats/baseapp_chats/graphql/subscriptions.py
- baseapp-chats/baseapp_chats/tests/test_graphql_mutations.py
- baseapp-chats/baseapp_chats/tests/test_graphql_subscriptions.py
- baseapp-chats/setup.cfg
- baseapp-profiles/baseapp_profiles/graphql/filters.py
- baseapp-profiles/setup.cfg
**Acceptance Criteria 
Context**
The only instance where we add members to groups is at the creation of the group, but in this story we want to enable adding members to an existing group (after creation)
**Business Rules - Add Member List**
- Adding a member is only enabled to admins
- Given I open the edit group page, I should see an "Add Member" option in the Members List section.
- Given I've clicked on the Add Member option, then the "Add Member Modal" should appear with a list of Contacts I can add to the Group
- The list should be sorted alphabetically
- The list should be scrollable vertically
- Each Contact card should display their profile pic, name and username
- While on the Add Member List, I should be able to select multiple contacts to add at once.
- Make sure that the …
> baseapp-chats: add members to existing group

- baseapp/setup.cfg
> baseapp-backend: bump version to 0.0.17

- baseapp/baseapp_core/tests/test_celery_beat_health_check.py
check is the task method is a task registered in Celery (instead of just a normal method)
> Improve celery_beat_health_check tests

- baseapp_core/graphql/utils.py
- baseapp_reports/graphql/queries.py
- baseapp_reports/tests/test_graphql_queries.py
- pytest.ini
- setup.cfg
- testproject/graphql.py
also deprecated ReportTypesQueries in favor of ReportsQueries
> baseapp_core[graphql]: fix conflict with get_obj_from_relay_id and query_optimizer

- baseapp/__init__.py
- pyproject.toml
- setup.cfg
Create package version dynamically from git tag
> baseapp: use git tag for versioning and remove hardcoded version

- baseapp_payments/serializers.py
- baseapp_payments/utils.py
- baseapp_payments/views.py
> baseapp_payments: add stripe api version

- README.md
- baseapp_payments/admin.py
- baseapp_payments/serializers.py
- baseapp_payments/utils.py
- baseapp_payments/views.py
Description
As a User, on the BaseApp Profile Page,I would like to manage my subscription plan, payment methods, and receive notifications for failed payment attempts, In order to easily update my subscription and payment details and ensure uninterrupted access.
Acceptance Criteria 
Frontend
Add a Subscription section to the settings menu.
Display the following details:
Current subscription plan.
Plan features.
Next billing date and amount.
Current payment method.
Include actions:
Change Plan button to navigate to the subscription options page.
Cancel Subscription button that opens a confirmation modal.
Display a dropdown menu under Payment Method:
Show all saved payment methods.
Allow users to select a different payment method.
If you change the payment method then display a toast …
> baseapp_payments: Stripe Checkout - Subscription Management Page

- baseapp_payments/serializers.py
- baseapp_payments/utils.py
- baseapp_payments/views.py
✅ Stripe Checkout - Payment Methods Management
Description
As a User, on the BaseApp Profile Page,I would like to add, view, update, and remove my saved payment methods in the settings menu, In order to manage my payment options easily and ensure uninterrupted payments.
Acceptance Criteria 
Frontend
Add a Payment Methods section to the settings menu.
Display a list of saved payment methods, including:
Card type and masked card number (e.g., Visa **** 1234).
Expiration date.
"Default" label for the primary payment method.
Include actions for each payment method via a hamburger menu:
Set as Default: Mark a selected payment method as the primary option for transactions.
Remove: Open a confirmation modal to delete the selected payment method.
Include a "+ Add Payment Method" button that: …
> baseapp_payments: Payment methods management

- baseapp_auth/anonymization.py
- baseapp_auth/emails.py
- baseapp_auth/models.py
- baseapp_auth/rest_framework/users/tasks.py
- baseapp_auth/rest_framework/users/views.py
- baseapp_auth/templates/users/emails/anonymize-user-error-body.html.j2
- baseapp_auth/templates/users/emails/anonymize-user-error-body.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-error-subject.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-error-superuser-body.html.j2
- baseapp_auth/templates/users/emails/anonymize-user-error-superuser-body.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-error-superuser-subject.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-success-body.html.j2
- baseapp_auth/templates/users/emails/anonymize-user-success-body.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-success-subject.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-success-superuser-body.html.j2
- baseapp_auth/templates/users/emails/anonymize-user-success-superuser-body.txt.j2
- baseapp_auth/templates/users/emails/anonymize-user-success-superuser-subject.txt.j2
- baseapp_chats/tests/test_users.py
- testproject/settings.py
Description
As a User, on the iOS,I would like to Have the ability to delete my account directly from the app, In order to Maintain control over my personal data and meet App Store compliance requirements.
Acceptance Criteria 
Description  
Add an option for users to delete their account within the mobile app
Place the "Delete Account" option under the Settings or Profile
Include a confirmation step before deletion is executed to prevent accidental removal
Display a clear message explaining that deletion is permanent and that your data will be anonymized
Upon confirmation, trigger backend process to anonymize user data
Update frontend to reflect account removal (e.g., navigate to Sign In screen after deletion)
Ensure deletion logs are properly captured for audit purposes
Acceptance …
> BaseApp APP - Account Deletion - Anonimize comments and messages (merging into epic branch)
